spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/web-services?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username:
    password:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    #sql:
    # init:
    #  mode: always
  jpa:
    # Choose either MySQL 8 or MySQL 5 below
    # For MySQL 8
    database-platform: org.hibernate.dialect.MySQL8Dialect
    #For MySQL 5
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  #Cloudinary Properties
  #cloudinary:
  #api-key:
  #api-secret:
  #cloud-name:

  #server:
    #port: 8081

  bezkoder:
    app:
      jwtSecret: bezKoderSecretKey
      jwtExpirationMs: 86400000

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 981849740643-dgmgth3b5pudk7di0bb4gaqbv1cr1glk.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

cloudinary:
  cloud-name: https-github-com-vankoivanov-web-service
  api-key: 654829793914841
  api-secret: "${CLOUDINARY_API_SECRET}"

